# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "virtio_pci" "virtio_scsi" "xhci_pci" "sd_mod" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/vda";
  boot.loader.grub.useOSProber = true;

  # Use latest kernel.
  boot.kernelPackages = pkgs.linuxPackages_latest;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b19c99e6-3163-4041-a1bd-bd12b83ec113";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/88391961-da8c-43ac-97dd-1b02bed0ca99"; }
    ];
    
  networking.interfaces.enp3s0 = {
    ipv4.addresses = [{
      address = "45.8.201.111";
      prefixLength = 24;
    }];
  };
  networking.defaultGateway = {
    address = "45.8.201.1";
    interface = "enp3s0";
  };
  networking.nameservers = [ "1.1.1.1" "8.8.8.8" ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
